### ISSUE TITLE
!rs vip bug?

### ISSUE THREAD

**Issue by freakexeuLow** [Javierko/CSGO-Advanced-ResetScore#1]
Hey, thanks for the great plugin. :) 

But I have a problem, some VIP users report that they can't use the !rs from time to time, but the other VIP stuff I use on my server works perfectly.

**Comment by Javierko** [comment]
Do you have any errors in your e. log?

Also I made an update today, so you can try it.

**Comment by freakexeuLow** [comment]
@Javierko not really, no error logs or something and thanks, i try it with the new version

**Comment by Javierko** [comment]
Some results? Works fine after the update?

**Comment by freakexeuLow** [comment]
> Some results? Works fine after the update?

hey and I haven't had a problem with this yet, I'll close the ticket when I'm 100% sure it will work. Im waiting for some messages from the users that wrote me the bug^^

**Comment by Javierko** [comment]
Ok, thanks for info.

**Comment by freakexeuLow** [comment]
I'm going to close the issue, there hasn't been a complaint yet. If something should be, I'll get back to you, thanks for your time.

**Comment by freakexeuLow** [comment]
Hey Javierko :)
Is it possible that the plugin can lose the connection? (its german, it say: [SM] This command can only be used by VIP's!)
Screenshot (the guy is VIP): [https://i.imgur.com/v3d4AVi.png](https://i.imgur.com/v3d4AVi.png) 
but he can not use !rs everytime...a admin wrote me this: but swanii (vip guy) tried it 20min into the map...so idk. So he wrote after this message this here: Admin: but it does work sometimes Admin:I never have this problem tho

The Owner Flag is "z" thats ONLY my Flag, the admin has the flag a,b,c,d,e,f,g,j,k,n Custom Flag: o,p
AdvancedResetScore.cfg: [https://pastebin.com/3YqiAVp7](https://pastebin.com/3YqiAVp7)

**Comment by Javierko** [comment]
Don't think so, I will try it on my server.

Do you have any errors in error log?

**Comment by freakexeuLow** [comment]
> 
> 
> Don't think so, I will try it on my server.
> 
> Do you have any errors in error log?

thank you and I have no any Errors in the logs :/

**Comment by Javierko** [comment]
Try it now.

**Comment by freakexeuLow** [comment]
> 
> 
> Try it now.

One question, had you had the same problems? And thanks, I will try it :)

**Comment by Javierko** [comment]
When I tried it, it works

**Comment by freakexeuLow** [comment]
> 
> 
> When I tried it, it works

Okay, if there are no more complaints, I will close the issue and thanks for the quick update

**Comment by freakexeuLow** [comment]
Hey Javierko, its me again and the problem still exists ^^
https://i.gyazo.com/e2305c7e54983d07c37a3da3a94e260f.png

**Comment by Javierko** [comment]
Interesting, can you please add me on Discord? (Javierko#8200)
I'll give you plugin version with debug messages.

**Comment by freakexeuLow** [comment]
> 
> 
> Interesting, can you please add me on Discord? (Javierko#8200)
> I'll give you plugin version with debug messages.

done
